fix: Upgrade to C++ 20 to fix compilation failures on Linux
* See: https://github.com/gabime/spdlog/issues/3233

* error 1:
    * tweakme.h:107:88: error: call to non-‘constexpr’ function
    * include/spdlog/common-inl.h:19:47: note: in expansion of macro ‘SPDLOG_LEVEL_NAMES’
* error 2:
    * the value of ‘leftAlign’ is not usable in a constant expression